package component.mybatis.entity;

import java.util.Date;

public class TTest1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.inspection_name
     *
     * @mbg.generated
     */
    private String inspectionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.order_no
     *
     * @mbg.generated
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.expect_result
     *
     * @mbg.generated
     */
    private String expectResult;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.msg_on_unexpected
     *
     * @mbg.generated
     */
    private String msgOnUnexpected;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.inspection_sql
     *
     * @mbg.generated
     */
    private String inspectionSql;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.parameters
     *
     * @mbg.generated
     */
    private String parameters;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_test_1.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.id
     *
     * @return the value of t_test_1.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.id
     *
     * @param id the value for t_test_1.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.inspection_name
     *
     * @return the value of t_test_1.inspection_name
     *
     * @mbg.generated
     */
    public String getInspectionName() {
        return inspectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.inspection_name
     *
     * @param inspectionName the value for t_test_1.inspection_name
     *
     * @mbg.generated
     */
    public void setInspectionName(String inspectionName) {
        this.inspectionName = inspectionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.order_no
     *
     * @return the value of t_test_1.order_no
     *
     * @mbg.generated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.order_no
     *
     * @param orderNo the value for t_test_1.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.expect_result
     *
     * @return the value of t_test_1.expect_result
     *
     * @mbg.generated
     */
    public String getExpectResult() {
        return expectResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.expect_result
     *
     * @param expectResult the value for t_test_1.expect_result
     *
     * @mbg.generated
     */
    public void setExpectResult(String expectResult) {
        this.expectResult = expectResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.msg_on_unexpected
     *
     * @return the value of t_test_1.msg_on_unexpected
     *
     * @mbg.generated
     */
    public String getMsgOnUnexpected() {
        return msgOnUnexpected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.msg_on_unexpected
     *
     * @param msgOnUnexpected the value for t_test_1.msg_on_unexpected
     *
     * @mbg.generated
     */
    public void setMsgOnUnexpected(String msgOnUnexpected) {
        this.msgOnUnexpected = msgOnUnexpected;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.inspection_sql
     *
     * @return the value of t_test_1.inspection_sql
     *
     * @mbg.generated
     */
    public String getInspectionSql() {
        return inspectionSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.inspection_sql
     *
     * @param inspectionSql the value for t_test_1.inspection_sql
     *
     * @mbg.generated
     */
    public void setInspectionSql(String inspectionSql) {
        this.inspectionSql = inspectionSql;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.parameters
     *
     * @return the value of t_test_1.parameters
     *
     * @mbg.generated
     */
    public String getParameters() {
        return parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.parameters
     *
     * @param parameters the value for t_test_1.parameters
     *
     * @mbg.generated
     */
    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.remark
     *
     * @return the value of t_test_1.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.remark
     *
     * @param remark the value for t_test_1.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.create_time
     *
     * @return the value of t_test_1.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.create_time
     *
     * @param createTime the value for t_test_1.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_test_1.update_time
     *
     * @return the value of t_test_1.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_test_1.update_time
     *
     * @param updateTime the value for t_test_1.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}