package com.shiro.dao;

import com.shiro.entity.module.TUserLoginInfo;
import java.util.List;

public interface TUserLoginInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_info
     *
     * @mbggenerated
     */
    int insert(TUserLoginInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_info
     *
     * @mbggenerated
     */
    TUserLoginInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_info
     *
     * @mbggenerated
     */
    List<TUserLoginInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_user_login_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TUserLoginInfo record);
}