package component.mybatis.mapper;

import component.mybatis.entity.TTest1;
import java.util.List;

public interface TTest1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_1
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_1
     *
     * @mbg.generated
     */
    int insert(TTest1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_1
     *
     * @mbg.generated
     */
    TTest1 selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_1
     *
     * @mbg.generated
     */
    List<TTest1> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_test_1
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTest1 record);
}