package com.shiro.entity.module;

import java.util.Date;

public class TPermission {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.module_code
     *
     * @mbggenerated
     */
    private String moduleCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.perm_code
     *
     * @mbggenerated
     */
    private String permCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.perm_name
     *
     * @mbggenerated
     */
    private String permName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.available
     *
     * @mbggenerated
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.modify_by
     *
     * @mbggenerated
     */
    private String modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission.edition
     *
     * @mbggenerated
     */
    private Integer edition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.id
     *
     * @return the value of t_permission.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.id
     *
     * @param id the value for t_permission.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.module_code
     *
     * @return the value of t_permission.module_code
     *
     * @mbggenerated
     */
    public String getModuleCode() {
        return moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.module_code
     *
     * @param moduleCode the value for t_permission.module_code
     *
     * @mbggenerated
     */
    public void setModuleCode(String moduleCode) {
        this.moduleCode = moduleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.module_name
     *
     * @return the value of t_permission.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.module_name
     *
     * @param moduleName the value for t_permission.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.perm_code
     *
     * @return the value of t_permission.perm_code
     *
     * @mbggenerated
     */
    public String getPermCode() {
        return permCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.perm_code
     *
     * @param permCode the value for t_permission.perm_code
     *
     * @mbggenerated
     */
    public void setPermCode(String permCode) {
        this.permCode = permCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.perm_name
     *
     * @return the value of t_permission.perm_name
     *
     * @mbggenerated
     */
    public String getPermName() {
        return permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.perm_name
     *
     * @param permName the value for t_permission.perm_name
     *
     * @mbggenerated
     */
    public void setPermName(String permName) {
        this.permName = permName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.description
     *
     * @return the value of t_permission.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.description
     *
     * @param description the value for t_permission.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.available
     *
     * @return the value of t_permission.available
     *
     * @mbggenerated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.available
     *
     * @param available the value for t_permission.available
     *
     * @mbggenerated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.create_by
     *
     * @return the value of t_permission.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.create_by
     *
     * @param createBy the value for t_permission.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.create_time
     *
     * @return the value of t_permission.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.create_time
     *
     * @param createTime the value for t_permission.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.modify_by
     *
     * @return the value of t_permission.modify_by
     *
     * @mbggenerated
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.modify_by
     *
     * @param modifyBy the value for t_permission.modify_by
     *
     * @mbggenerated
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.modify_time
     *
     * @return the value of t_permission.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.modify_time
     *
     * @param modifyTime the value for t_permission.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_permission.edition
     *
     * @return the value of t_permission.edition
     *
     * @mbggenerated
     */
    public Integer getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_permission.edition
     *
     * @param edition the value for t_permission.edition
     *
     * @mbggenerated
     */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }
}