package com.shiro.entity.module;

import java.util.Date;

public class TRole {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.super_admin
     *
     * @mbggenerated
     */
    private Boolean superAdmin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.available
     *
     * @mbggenerated
     */
    private Boolean available;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_by
     *
     * @mbggenerated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.modify_by
     *
     * @mbggenerated
     */
    private String modifyBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_role.edition
     *
     * @mbggenerated
     */
    private Integer edition;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.id
     *
     * @return the value of t_role.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.id
     *
     * @param id the value for t_role.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.role_name
     *
     * @return the value of t_role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.role_name
     *
     * @param roleName the value for t_role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.description
     *
     * @return the value of t_role.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.description
     *
     * @param description the value for t_role.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.super_admin
     *
     * @return the value of t_role.super_admin
     *
     * @mbggenerated
     */
    public Boolean getSuperAdmin() {
        return superAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.super_admin
     *
     * @param superAdmin the value for t_role.super_admin
     *
     * @mbggenerated
     */
    public void setSuperAdmin(Boolean superAdmin) {
        this.superAdmin = superAdmin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.available
     *
     * @return the value of t_role.available
     *
     * @mbggenerated
     */
    public Boolean getAvailable() {
        return available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.available
     *
     * @param available the value for t_role.available
     *
     * @mbggenerated
     */
    public void setAvailable(Boolean available) {
        this.available = available;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_by
     *
     * @return the value of t_role.create_by
     *
     * @mbggenerated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_by
     *
     * @param createBy the value for t_role.create_by
     *
     * @mbggenerated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.create_time
     *
     * @return the value of t_role.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.create_time
     *
     * @param createTime the value for t_role.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.modify_by
     *
     * @return the value of t_role.modify_by
     *
     * @mbggenerated
     */
    public String getModifyBy() {
        return modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.modify_by
     *
     * @param modifyBy the value for t_role.modify_by
     *
     * @mbggenerated
     */
    public void setModifyBy(String modifyBy) {
        this.modifyBy = modifyBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.modify_time
     *
     * @return the value of t_role.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.modify_time
     *
     * @param modifyTime the value for t_role.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_role.edition
     *
     * @return the value of t_role.edition
     *
     * @mbggenerated
     */
    public Integer getEdition() {
        return edition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_role.edition
     *
     * @param edition the value for t_role.edition
     *
     * @mbggenerated
     */
    public void setEdition(Integer edition) {
        this.edition = edition;
    }
}