package org.seckill.module;

import java.util.Date;

public class TSeckill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.seckill_id
     *
     * @mbggenerated
     */
    protected Long seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.name
     *
     * @mbggenerated
     */
    protected String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.number
     *
     * @mbggenerated
     */
    protected Integer number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.start_time
     *
     * @mbggenerated
     */
    protected Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.end_time
     *
     * @mbggenerated
     */
    protected Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill.create_time
     *
     * @mbggenerated
     */
    protected Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.seckill_id
     *
     * @return the value of seckill.seckill_id
     *
     * @mbggenerated
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.seckill_id
     *
     * @param seckillId the value for seckill.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.name
     *
     * @return the value of seckill.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.name
     *
     * @param name the value for seckill.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.number
     *
     * @return the value of seckill.number
     *
     * @mbggenerated
     */
    public Integer getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.number
     *
     * @param number the value for seckill.number
     *
     * @mbggenerated
     */
    public void setNumber(Integer number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.start_time
     *
     * @return the value of seckill.start_time
     *
     * @mbggenerated
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.start_time
     *
     * @param startTime the value for seckill.start_time
     *
     * @mbggenerated
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.end_time
     *
     * @return the value of seckill.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.end_time
     *
     * @param endTime the value for seckill.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill.create_time
     *
     * @return the value of seckill.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill.create_time
     *
     * @param createTime the value for seckill.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}