package org.seckill.module;

import org.seckill.entitiy.Seckill;

import java.util.Date;

public class TSuccessKilled {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.seckill_id
     *
     * @mbggenerated
     */
    protected Long seckillId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.user_phone
     *
     * @mbggenerated
     */
    protected Long userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.state
     *
     * @mbggenerated
     */
    protected short state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column success_killed.create_time
     *
     * @mbggenerated
     */
    protected Date createTime;

    private TSeckill seckill;

    public TSeckill getSeckill() {
        return seckill;
    }

    public void setSeckill(TSeckill seckill) {
        this.seckill = seckill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.seckill_id
     *
     * @return the value of success_killed.seckill_id
     *
     * @mbggenerated
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.seckill_id
     *
     * @param seckillId the value for success_killed.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.user_phone
     *
     * @return the value of success_killed.user_phone
     *
     * @mbggenerated
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.user_phone
     *
     * @param userPhone the value for success_killed.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.state
     *
     * @return the value of success_killed.state
     *
     * @mbggenerated
     */
    public short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.state
     *
     * @param state the value for success_killed.state
     *
     * @mbggenerated
     */
    public void setState(short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column success_killed.create_time
     *
     * @return the value of success_killed.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column success_killed.create_time
     *
     * @param createTime the value for success_killed.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}